export const CELL_WIDTH = 182
export const CELL_HEIGHT = 138
export const REELS_COUNT = 5
export const MINIMAL_REGULAR_REEL_LENGTH = 3
export const MAXIMAL_REGULAR_REEL_LENGTH = 7
export const REELS_LENGTHS = [
	1,
	MAXIMAL_REGULAR_REEL_LENGTH,
	MAXIMAL_REGULAR_REEL_LENGTH,
	MAXIMAL_REGULAR_REEL_LENGTH,
	1
]
export const REELS_WIDTH = REELS_COUNT * CELL_WIDTH
export const REELS_HEIGHT = MAXIMAL_REGULAR_REEL_LENGTH * CELL_HEIGHT
export const SCATTER_SYMBOL_ID = 11
export const WILD_SYMBOL_ID = 12

export const RANDOM_REELS_SYMBOLS_IDS = [
	[0, 6, 7, 8, 9, 10],
	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	[0, 6, 7, 8, 9, 10],
]
export const TURBO_MODE_TIME_SCALE = 2
export const REGULAR_SYMBOLS_IDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
export const POSSIBLE_REELS_SYMBOLS = [
	[...REGULAR_SYMBOLS_IDS, SCATTER_SYMBOL_ID, WILD_SYMBOL_ID ],
	[...REGULAR_SYMBOLS_IDS, SCATTER_SYMBOL_ID],
	[...REGULAR_SYMBOLS_IDS, SCATTER_SYMBOL_ID],
	[...REGULAR_SYMBOLS_IDS, SCATTER_SYMBOL_ID],
	[...REGULAR_SYMBOLS_IDS, SCATTER_SYMBOL_ID ],
]
export const WIN_COEFFICIENTS = {
	BIG: 5,
	HUGE: 10,
	MEGA: 15,
}